#!/bin/bash
IF_ROOT=/opt/kip/App

# kipapp.co
cd "$IF_ROOT"
pm2 start IF_server.js

# instagram service
cd "$IF_ROOT"/IF_services/IF_instagram_REST_processer
pm2 start IF_instagram_server.js

# twitter service
cd "$IF_ROOT"/IF_services/IF_tweet_REST_processer
pm2 start IF_tweet_server.js

# shmelp service
cd "$IF_ROOT"/IF_services/IF_forage/yelp
pm2 start IF_forage_yelp.js

# meetup
cd "$IF_ROOT"/IF_services/IF_forage/meetup
pm2 start IF_forage_meetup.js

# geoip
#cd "$IF_ROOT"/../go/bin
#setsid ./freegeoip >freegeoip.log 2>freegeoip.err.log
